In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import sklearn.metrics as metrics
import ipynb
from ipynb.fs.full.Data_prep import *
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import seaborn as sns
from sklearn.feature_selection import f_regression

TIME_PERIODS = 200
STEP_DISTANCE = 200

In [49]:
#Normalize before and After

# dataset = pd.read_csv('watch.csv')
# # print(dataset)
# column_names = dataset.keys()
# Dataset = normalize(dataset, axis=0)
# Dataset = pd.DataFrame(Dataset, columns=column_names)
# Dataset['user-id'] = dataset['user-id']
# Dataset['timestamp'] = dataset['timestamp']
# Dataset['activity'] = dataset['activity']
# # print(Dataset)
# test, train = split_test_train(Dataset, 'user-id', 0.8)
# # print(test.shape)
# # print(train.shape)
# x_train, y_train = segment(train, TIME_PERIODS, STEP_DISTANCE, 'activity', train.columns.difference(['activity','user-id','timestamp']), 'user-id')
# x_test, y_test = segment(test, TIME_PERIODS, STEP_DISTANCE, 'activity', test.columns.difference(['activity','user-id','timestamp']), 'user-id')
# # print(x_train.shape, y_train.shape)
# # print(x_test.shape, y_test.shape)
# x_test_n = change_segments(x_test)
# x_train_n = change_segments(x_train)
# # print(x_test_n)
# # print(x_train_n)
# # print(x_test_n.shape, ',', y_test.shape)
# # print(x_train_n.shape, ',', y_train.shape)

(2959, 200, 6)
(11562, 200, 6)


In [50]:
# with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
#     print(x_test_n)

[[1.0000 0.0000 2.0000 ... 4.1304 0.0008 0.0006]
 [3.0000 10.0000 23.0000 ... 4.2391 0.0008 0.0007]
 [5.0000 32.0000 25.0000 ... 4.0889 0.0007 0.0006]
 ...
 [1.0000 0.0000 1.0000 ... 4.5581 0.0000 0.0000]
 [1.0000 0.0000 4.0000 ... 4.4545 0.0001 0.0001]
 [1.0000 0.0000 1.0000 ... 4.6190 0.0001 0.0001]]


In [52]:
# # transformer = Normalizer().fit(x_train_n)
# transformer = StandardScaler().fit(x_train_n)
# x_train_n = transformer.transform(x_train_n)
# x_test_n = transformer.transform(x_test_n)
# with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
#     print(x_test_n)

[[-0.3664 -0.6650 -0.8355 ... -0.5030 0.8776 0.9710]
 [-0.2273 -0.0043 0.2214 ... -0.4464 0.9016 1.0675]
 [-0.0882 1.4490 0.3220 ... -0.5247 0.7920 0.9037]
 ...
 [-0.3664 -0.6650 -0.8859 ... -0.2801 -0.5031 -0.4815]
 [-0.3664 -0.6650 -0.7349 ... -0.3341 -0.3753 -0.3395]
 [-0.3664 -0.6650 -0.8859 ... -0.2484 -0.2961 -0.2790]]


In [53]:
# param_grid_in = [
# #             {'C': [0.01, 0.001, 0.0001],
# #              'tol': [1, 0.01, 0.001, 0.0001],
# #              'max_iter': [-1, 1000, 5000],
#              {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
#              'degree': [2], #,3
#              'class_weight': ['balanced']}
# #              'gamma': [1, 0.1, 0.001, 0.0001, 0.00001],
# #              'decision_function_shape': ['ovo', 'ovr'],  # one-vs-one/one-vs-rest
# #              'class_weight': ['balanced']}  # auto balance the weight
#         ]
# clf = SVC()
# svm_model = GridSearchCV(clf, param_grid=param_grid_in, cv=10, n_jobs=4, error_score=np.nan, verbose=0) 
# svm_model = svm_model.fit(x_train_n, y_train)
# y_pred = svm_model.predict(x_test_n)
# acc = metrics.accuracy_score(y_test, y_pred, normalize=True)
# print(acc)

0.21561338289962825


In [57]:
# # train the model and time the training
# #     start_time = time.time()
# #     svm_model = svm_model.fit(x_train_in, y_train_in)
# #     end_time = time.time()

# # print time for training
# # print('\nTraining takes ', end_time - start_time, 's\n')

# # print the best hyper-parameters
# print('\nClass weight option:', svm_model.best_estimator_.get_params()['class_weight'])
# print('Best kernel:', svm_model.best_estimator_.get_params()['kernel'])
# print('Best polynomial degree:', svm_model.best_estimator_.get_params()['degree'])
# print('Best gamma:', svm_model.best_estimator_.get_params()['gamma'])
# print('Best C:', svm_model.best_estimator_.get_params()['C'])
# print('Best tolerance:', svm_model.best_estimator_.get_params()['tol'])
# print('Best max number of iterations', svm_model.best_estimator_.get_params()['max_iter'])
# print('Best decision function shape option', svm_model.best_estimator_.get_params()['decision_function_shape'],
#       '\n')

# # print the accuracy scores
# y_pred = svm_model.predict(x_test_n)
# result = metrics.accuracy_score(y_test, y_pred)
# result_2 = metrics.balanced_accuracy_score(y_test, y_pred)
# print('The accuracy score is: ', result)
# print('The balanced accuracy score is: ', result_2)


Class weight option: None
Best kernel: rbf
Best polynomial degree: 2
Best gamma: auto_deprecated
Best C: 1.0
Best tolerance: 0.001
Best max number of iterations -1
Best decision function shape option ovr 

The accuracy score is:  0.21561338289962825
The balanced accuracy score is:  0.22347320825903422


In [3]:
#Give in the raw data

# dataset = pd.read_csv('phone.csv')
# column_names = dataset.keys()
# test, train = split_test_train(dataset, 'user-id', 0.8)
# y_test = test['activity'].to_numpy().T.astype(float)
# x_test = test.drop(columns=['activity'])
# y_train = test['activity'].to_numpy().T.astype(float)
# print(y_train.shape)
# x_train = test.drop(columns=['activity'])
# transformer = StandardScaler().fit(x_train)
# x_train_n = transformer.transform(x_train)
# x_test_n = transformer.transform(x_test)
# print(x_train_n.shape)
# with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
#     print(x_test_n)
# param_grid_in = [
# #             {'C': [0.01, 0.001, 0.0001],
# #              'tol': [1, 0.01, 0.001, 0.0001],
# #              'max_iter': [-1, 1000, 5000],
#              {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
#              'degree': [2], # ,3
#              'class_weight': ['balanced']}
# #              'gamma': [1, 0.1, 0.001, 0.0001, 0.00001],
# #              'decision_function_shape': ['ovo', 'ovr'],  # one-vs-one/one-vs-rest
# #              'class_weight': ['balanced']}  # auto balance the weight
#         ]
# clf = SVC()
# svm_model = GridSearchCV(clf, param_grid=param_grid_in, cv=10, n_jobs=4, error_score=np.nan, verbose=0) 
# svm_model = svm_model.fit(x_train_n, y_train)
# y_pred = svm_model.predict(x_test_n)
# acc = metrics.accuracy_score(y_test, y_pred, normalize=True)
print(acc)

(645031,)
(645031, 8)
[[-1.2587 -0.4021 -0.8431 ... -0.9908 0.3575 1.2601]
 [-1.2587 -0.4021 -0.0951 ... -1.0163 0.0299 0.2306]
 [-1.2587 -0.4021 0.2563 ... -0.8358 0.4636 -0.4004]
 ...
 [1.6057 0.9805 -0.0977 ... -0.0550 0.4516 -0.2037]
 [1.6057 0.9805 -0.1637 ... -0.1295 0.3761 -0.1525]
 [1.6057 0.9805 -0.1119 ... -0.1717 0.2225 -0.0244]]


KeyboardInterrupt: 

In [ ]:
# # train the model and time the training
# #     start_time = time.time()
# #     svm_model = svm_model.fit(x_train_in, y_train_in)
# #     end_time = time.time()

#     # print time for training
#     print('\nTraining takes ', end_time - start_time, 's\n')

#     # print the best hyper-parameters
#     print('\nClass weight option:', svm_model.best_estimator_.get_params()['class_weight'])
#     print('Best kernel:', svm_model.best_estimator_.get_params()['kernel'])
#     print('Best polynomial degree:', svm_model.best_estimator_.get_params()['degree'])
#     print('Best gamma:', svm_model.best_estimator_.get_params()['gamma'])
#     print('Best C:', svm_model.best_estimator_.get_params()['C'])
#     print('Best tolerance:', svm_model.best_estimator_.get_params()['tol'])
#     print('Best max number of iterations', svm_model.best_estimator_.get_params()['max_iter'])
#     print('Best decision function shape option', svm_model.best_estimator_.get_params()['decision_function_shape'],
#           '\n')

#     # print the accuracy scores
#     y_pred = svm_model.predict(x_test_in)
#     result = metrics.accuracy_score(y_test_in, y_pred)
#     result_2 = metrics.balanced_accuracy_score(y_test_in, y_pred)
#     print('The accuracy score is: ', result)
#     print('The balanced accuracy score is: ', result_2)

In [6]:
#Normalizer or Standard Scaler only after feature extraction

dataset = pd.read_csv('watch.csv')
# print(dataset)
column_names = dataset.keys()
# Dataset = normalize(dataset, axis=0)
# Dataset = pd.DataFrame(Dataset, columns=column_names)
# Dataset['user-id'] = dataset['user-id']
# Dataset['timestamp'] = dataset['timestamp']
# Dataset['activity'] = dataset['activity']
# print(Dataset)
test, train = split_test_train(dataset, 'user-id', 0.8)
# print(test.shape)
# print(train.shape)
x_train, y_train = segment(train, TIME_PERIODS, STEP_DISTANCE, 'activity', train.columns.difference(['activity','user-id','timestamp']), 'user-id')
x_test, y_test = segment(test, TIME_PERIODS, STEP_DISTANCE, 'activity', test.columns.difference(['activity','user-id','timestamp']), 'user-id')
# print(x_train.shape, y_train.shape)
# print(x_test.shape, y_test.shape)
x_test_n = change_segments(x_test)
x_train_n = change_segments(x_train)
# print(x_test_n)
# print(x_train_n)
# print(x_test_n.shape, ',', y_test.shape)
# print(x_train_n.shape, ',', y_train.shape)

(3278, 200, 6)
(13542, 200, 6)


In [7]:
transformer = Normalizer().fit(x_train_n) # Normalization = 0.49
# transformer = StandardScaler().fit(x_train_n) # StandardScaler = 0.7%
x_train_n = transformer.transform(x_train_n)
x_test_n = transformer.transform(x_test_n)
with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
    print(x_test_n)

[[0.0390 0.0000 0.0146 ... 0.0456 0.0078 0.0063]
 [0.1089 0.2015 0.1307 ... 0.0473 0.0078 0.0064]
 [0.0183 0.0319 0.0958 ... 0.0388 0.0068 0.0055]
 ...
 [0.0039 0.0237 0.1261 ... 0.0195 0.0079 0.0046]
 [0.0661 0.0623 0.1128 ... 0.0258 0.0071 0.0045]
 [0.0209 0.0585 0.1754 ... 0.0237 0.0044 0.0030]]


In [8]:
param_grid_in = [
#             {'C': [0.01, 0.001, 0.0001],
#              'tol': [1, 0.01, 0.001, 0.0001],
#              'max_iter': [-1, 1000, 5000],
             {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
             'degree': [2], # ,3
             'class_weight': ['balanced']}
#              'gamma': [1, 0.1, 0.001, 0.0001, 0.00001],
#              'decision_function_shape': ['ovo', 'ovr'],  # one-vs-one/one-vs-rest
#              'class_weight': ['balanced']}  # auto balance the weight
        ]
clf = SVC()
svm_model = GridSearchCV(clf, param_grid=param_grid_in, cv=10, n_jobs=4, error_score=np.nan, verbose=0) 
svm_model = svm_model.fit(x_train_n, y_train)
y_pred = svm_model.predict(x_test_n)
acc = metrics.accuracy_score(y_test, y_pred, normalize=True)
print(acc)

0.4978645515558267


In [9]:
# train the model and time the training
#     start_time = time.time()
#     svm_model = svm_model.fit(x_train_in, y_train_in)
#     end_time = time.time()

# print time for training
# print('\nTraining takes ', end_time - start_time, 's\n')

# print the best hyper-parameters
print('\nClass weight option:', svm_model.best_estimator_.get_params()['class_weight'])
print('Best kernel:', svm_model.best_estimator_.get_params()['kernel'])
print('Best polynomial degree:', svm_model.best_estimator_.get_params()['degree'])
print('Best gamma:', svm_model.best_estimator_.get_params()['gamma'])
print('Best C:', svm_model.best_estimator_.get_params()['C'])
print('Best tolerance:', svm_model.best_estimator_.get_params()['tol'])
print('Best max number of iterations', svm_model.best_estimator_.get_params()['max_iter'])
print('Best decision function shape option', svm_model.best_estimator_.get_params()['decision_function_shape'],
      '\n')

# print the accuracy scores
y_pred = svm_model.predict(x_test_n)
result = metrics.accuracy_score(y_test, y_pred)
result_2 = metrics.balanced_accuracy_score(y_test, y_pred)
print('The accuracy score is: ', result)
print('The balanced accuracy score is: ', result_2)


Class weight option: balanced
Best kernel: linear
Best polynomial degree: 2
Best gamma: auto_deprecated
Best C: 1.0
Best tolerance: 0.001
Best max number of iterations -1
Best decision function shape option ovr 

The accuracy score is:  0.4978645515558267
The balanced accuracy score is:  0.4987370163787962


In [10]:
#MinMax

dataset = pd.read_csv('watch.csv')
# print(dataset)
column_names = dataset.keys()
# Dataset = normalize(dataset, axis=0)
# Dataset = pd.DataFrame(Dataset, columns=column_names)
# Dataset['user-id'] = dataset['user-id']
# Dataset['timestamp'] = dataset['timestamp']
# Dataset['activity'] = dataset['activity']
# print(Dataset)
test, train = split_test_train(dataset, 'user-id', 0.8)
# print(test.shape)
# print(train.shape)
x_train, y_train = segment(train, TIME_PERIODS, STEP_DISTANCE, 'activity', train.columns.difference(['activity','user-id','timestamp']), 'user-id')
x_test, y_test = segment(test, TIME_PERIODS, STEP_DISTANCE, 'activity', test.columns.difference(['activity','user-id','timestamp']), 'user-id')
# print(x_train.shape, y_train.shape)
# print(x_test.shape, y_test.shape)
x_test_n = change_segments(x_test)
x_train_n = change_segments(x_train)
# print(x_test_n)
# print(x_train_n)
# print(x_test_n.shape, ',', y_test.shape)
# print(x_train_n.shape, ',', y_train.shape)

(2588, 200, 6)
(14232, 200, 6)


In [11]:
transformer = preprocessing.MinMaxScaler().fit(x_train_n) #MinMax = 0.65%
x_train_n = transformer.transform(x_train_n)
x_test_n = transformer.transform(x_test_n)
with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
    print(x_test_n)

[[0.0510 0.0585 0.0471 ... 0.0381 0.3039 0.2582]
 [0.0255 0.0319 0.1152 ... 0.0593 0.2651 0.2444]
 [0.0000 0.0638 0.2042 ... 0.0731 0.3219 0.3131]
 ...
 [0.0000 0.1489 0.1309 ... 0.0313 0.2366 0.1863]
 [0.0510 0.0691 0.0366 ... 0.0355 0.2081 0.1762]
 [0.1173 0.1649 0.0733 ... 0.0352 0.3017 0.2212]]


In [12]:
param_grid_in = [
#             {'C': [0.01, 0.001, 0.0001],
#              'tol': [1, 0.01, 0.001, 0.0001],
#              'max_iter': [-1, 1000, 5000],
             {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
             'degree': [2], # ,3
             'class_weight': ['balanced']}
#              'gamma': [1, 0.1, 0.001, 0.0001, 0.00001],
#              'decision_function_shape': ['ovo', 'ovr'],  # one-vs-one/one-vs-rest
#              'class_weight': ['balanced']}  # auto balance the weight
        ]
clf = SVC()
svm_model = GridSearchCV(clf, param_grid=param_grid_in, cv=10, n_jobs=4, error_score=np.nan, verbose=0) 
svm_model = svm_model.fit(x_train_n, y_train)
# train the model and time the training
#     start_time = time.time()
#     svm_model = svm_model.fit(x_train_in, y_train_in)
#     end_time = time.time()

# print time for training
# print('\nTraining takes ', end_time - start_time, 's\n')

# print the best hyper-parameters
print('\nClass weight option:', svm_model.best_estimator_.get_params()['class_weight'])
print('Best kernel:', svm_model.best_estimator_.get_params()['kernel'])
print('Best polynomial degree:', svm_model.best_estimator_.get_params()['degree'])
print('Best gamma:', svm_model.best_estimator_.get_params()['gamma'])
print('Best C:', svm_model.best_estimator_.get_params()['C'])
print('Best tolerance:', svm_model.best_estimator_.get_params()['tol'])
print('Best max number of iterations', svm_model.best_estimator_.get_params()['max_iter'])
print('Best decision function shape option', svm_model.best_estimator_.get_params()['decision_function_shape'],
      '\n')

# print the accuracy scores
y_pred = svm_model.predict(x_test_n)
result = metrics.accuracy_score(y_test, y_pred)
result_2 = metrics.balanced_accuracy_score(y_test, y_pred)
print('The accuracy score is: ', result)
print('The balanced accuracy score is: ', result_2)


Class weight option: balanced
Best kernel: linear
Best polynomial degree: 2
Best gamma: auto_deprecated
Best C: 1.0
Best tolerance: 0.001
Best max number of iterations -1
Best decision function shape option ovr 

The accuracy score is:  0.64258114374034
The balanced accuracy score is:  0.6457466664446995


In [14]:
def feature_selection_pearson(data, thresh):
    corr = data.corr()
    columns_to_remove = []
#     print(corr)
#     sns.heatmap(corr)
    columns = data.keys()# np.full((corr.shape[0],), True, dtype=bool)
#     print(columns)
#     print(corr.shape)
    for i in range(corr.shape[0]):
        for j in range(i+1, corr.shape[0]):
#             print(corr.iloc[i,j])
            if abs(corr.iloc[i,j]) >= thresh:
#                 print(j)
#                 np.delete(columns,j)
                columns_to_remove.append(j)
#                 print(j)
#                 if columns[j]:
#                     print('here')
#                     columns[j] = False
    columns_to_remove = np.array(columns_to_remove)
    columns_to_remove = np.unique(columns_to_remove)
#     selected_columns = data.columns[columns]
#     print(columns)
#     data = data[selected_columns]
    return columns_to_remove

def p_value(x, y, cutoff):
    columns_to_remove = []
    columns = x.keys()
    num_features = len(columns)
    raw_scores, p_values = f_regression(x, y)
    for i in range(num_features):
        if (p_values[i] > cutoff):
            columns_to_remove.append(i)
    columns_to_remove = np.array(columns_to_remove)
    columns_to_remove = np.unique(columns_to_remove)
    return columns_to_remove

In [29]:
# Using pearson Correlation feature selection

dataset = pd.read_csv('watch.csv')
# print(dataset)
column_names = dataset.keys()
# Dataset = normalize(dataset, axis=0)
# Dataset = pd.DataFrame(Dataset, columns=column_names)
# Dataset['user-id'] = dataset['user-id']
# Dataset['timestamp'] = dataset['timestamp']
# Dataset['activity'] = dataset['activity']
# print(Dataset)
# label = dataset['activity']
# user = dataset['user-id']
# timestamp = dataset['timestamp']
# dataset = dataset.drop(columns=['activity','user-id','timestamp'])
# dataset = feature_selection_pearson(dataset,0.99)
# dataset['activity'] = label
# dataset['user-id'] = user
# dataset['timestamp'] = timestamp
# print(dataset)
test, train = split_test_train(dataset, 'user-id', 0.8)
# print(test.shape)
# print(train.columns.difference(['activity','user-id','timestamp']))
x_train, y_train = segment(train, TIME_PERIODS, STEP_DISTANCE, 'activity', train.columns.difference(['activity','user-id','timestamp']), 'user-id')
x_test, y_test = segment(test, TIME_PERIODS, STEP_DISTANCE, 'activity', test.columns.difference(['activity','user-id','timestamp']), 'user-id')
# print(x_train.shape, y_train.shape)
# print(x_test.shape, y_test.shape)
# print(x_test)
x_test_n = change_segments(x_test)
x_train_n = change_segments(x_train)
# x_train_n_columns = feature_selection_pearson(pd.Dataframe(x_train_n), 0.9)
# print(x_test_n)
# print(x_train)
# print(x_test_n.shape, ',', y_test.shape)
# print(x_train_n.shape, ',', y_train.shape)

(2999, 200, 6)
(13821, 200, 6)


In [30]:
# print(pd.DataFrame(x_train_n))
x_train_n_1 = pd.DataFrame(x_train_n)
# print(x_train_n_1)
x_test_n_1 = pd.DataFrame(x_test_n)
# remove_columns = feature_selection_pearson(x_train_n_1, 0.9) #0.9 thresh, 78 columns
remove_columns = p_value(x_train_n_1, y_train, 0.05) #0.1 thresh, 69 columns - 0.05, 64 columns
x_train_n_1 = x_train_n_1.drop(columns=remove_columns)
x_test_n_1 = x_test_n_1.drop(columns=remove_columns)
print(x_train_n_1)

         0     2     3     4     7     8          10         11        12  \
0      15.0   6.0   2.0   5.0  39.0  28.0   8.884487   6.000000  7.174556   
1       9.0  38.0  33.0  28.0  14.0   4.0  11.671765  11.125000  3.586754   
2       9.0  26.0  40.0  26.0  23.0   6.0   2.329803   9.450000  4.586164   
3      12.0  22.0  32.0  37.0  24.0  22.0  11.295586   9.047619  4.226434   
4      18.0  17.0  39.0   0.0  19.0  37.0   5.061157   9.700000  8.701770   
...     ...   ...   ...   ...   ...   ...        ...        ...       ...   
13816   6.0  28.0  54.0  43.0   7.0   3.0  -1.349007   3.545455  0.317351   
13817   2.0  10.0  12.0  31.0  14.0   8.0  -1.354288   3.803922  0.503923   
13818   3.0   7.0   8.0  24.0  33.0   9.0  -1.251841   4.083333  0.389108   
13819   6.0  84.0  35.0   4.0   0.0   0.0  -1.107864   3.840000  0.395505   
13820   2.0  28.0  61.0  61.0   7.0   0.0  -1.243063   4.595238  0.500671   

             13  ...    72    73    75    76    77    79        80         

In [31]:
# transformer = Normalizer().fit(x_train_n_1) # pearson 0.9, acc 0.42
transformer = StandardScaler().fit(x_train_n_1) # pearson 0.9, acc 0.69; p-value 0.1, acc 0.69
# transformer = preprocessing.MinMaxScaler().fit(x_train_n_1) # pearson 0.9, acc 0.65; p-value 0.05, acc 0.64
x_train_n = transformer.transform(x_train_n_1)
x_test_n = transformer.transform(x_test_n_1)
with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
    print(x_test_n)

[[-0.2113 -0.5027 -0.7933 ... 0.8095 1.5447 1.8329]
 [-0.1587 -0.7875 -0.4980 ... 0.6397 1.9874 2.1346]
 [-0.3691 -0.8825 -0.7511 ... 0.8095 1.8949 2.1050]
 ...
 [-0.5795 0.2095 -0.2027 ... -0.2817 0.3975 0.2079]
 [-0.0535 -0.6451 -0.2871 ... -0.2232 0.2345 0.1479]
 [0.6302 -0.3128 -0.5824 ... -0.2276 0.7700 0.4169]]


In [32]:
param_grid_in = [
#             {'C': [0.01, 0.001, 0.0001],
#              'tol': [1, 0.01, 0.001, 0.0001],
#              'max_iter': [-1, 1000, 5000],
             {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
             'degree': [2], # ,3
             'class_weight': ['balanced']}
#              'gamma': [1, 0.1, 0.001, 0.0001, 0.00001],
#              'decision_function_shape': ['ovo', 'ovr'],  # one-vs-one/one-vs-rest
#              'class_weight': ['balanced']}  # auto balance the weight
        ]
clf = SVC()
svm_model = GridSearchCV(clf, param_grid=param_grid_in, cv=10, n_jobs=4, error_score=np.nan, verbose=0) 
svm_model = svm_model.fit(x_train_n, y_train)
# train the model and time the training
#     start_time = time.time()
#     svm_model = svm_model.fit(x_train_in, y_train_in)
#     end_time = time.time()

# print time for training
# print('\nTraining takes ', end_time - start_time, 's\n')

# print the best hyper-parameters
print('\nClass weight option:', svm_model.best_estimator_.get_params()['class_weight'])
print('Best kernel:', svm_model.best_estimator_.get_params()['kernel'])
print('Best polynomial degree:', svm_model.best_estimator_.get_params()['degree'])
print('Best gamma:', svm_model.best_estimator_.get_params()['gamma'])
print('Best C:', svm_model.best_estimator_.get_params()['C'])
print('Best tolerance:', svm_model.best_estimator_.get_params()['tol'])
print('Best max number of iterations', svm_model.best_estimator_.get_params()['max_iter'])
print('Best decision function shape option', svm_model.best_estimator_.get_params()['decision_function_shape'],
      '\n')

# print the accuracy scores
y_pred = svm_model.predict(x_test_n)
result = metrics.accuracy_score(y_test, y_pred)
result_2 = metrics.balanced_accuracy_score(y_test, y_pred)
print('The accuracy score is: ', result)
print('The balanced accuracy score is: ', result_2)


Class weight option: balanced
Best kernel: rbf
Best polynomial degree: 2
Best gamma: auto_deprecated
Best C: 1.0
Best tolerance: 0.001
Best max number of iterations -1
Best decision function shape option ovr 

The accuracy score is:  0.6898966322107369
The balanced accuracy score is:  0.6944319354389848
